/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers'
import { Provider, TransactionRequest } from '@ethersproject/providers'
import type {
  ERC20PercentageTest,
  ERC20PercentageTestInterface
} from '../ERC20PercentageTest'

const _abi = [
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'percentage',
        type: 'uint256'
      },
      {
        internalType: 'uint256',
        name: 'from',
        type: 'uint256'
      }
    ],
    name: 'take',
    outputs: [
      {
        internalType: 'uint256',
        name: '',
        type: 'uint256'
      }
    ],
    stateMutability: 'view',
    type: 'function'
  }
]

const _bytecode =
  '0x608060405234801561001057600080fd5b50610269806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063978b7c0214610030575b600080fd5b61004361003e3660046100d2565b610055565b60405190815260200160405180910390f35b60006100638383601261006c565b90505b92915050565b60008061009768056bc75e2d6310000061009161008a86600a610156565b88906100ba565b906100c6565b90506100b16100a784600a610156565b61009186846100ba565b95945050505050565b600061006382846101fe565b600061006382846100f3565b600080604083850312156100e4578182fd5b50508035926020909101359150565b60008261010e57634e487b7160e01b81526012600452602481fd5b500490565b600181815b8085111561014e5781600019048211156101345761013461021d565b8085161561014157918102915b93841c9390800290610118565b509250929050565b6000610063838360008261016c57506001610066565b8161017957506000610066565b816001811461018f5760028114610199576101b5565b6001915050610066565b60ff8411156101aa576101aa61021d565b50506001821b610066565b5060208310610133831016604e8410600b84101617156101d8575081810a610066565b6101e28383610113565b80600019048211156101f6576101f661021d565b029392505050565b60008160001904831182151516156102185761021861021d565b500290565b634e487b7160e01b600052601160045260246000fdfea264697066735822122045bc8c1228dc3ce0f323dda4a3137cfeaff939cfb15e9ba9d1d047e9555d166364736f6c63430008040033'

export class ERC20PercentageTest__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer)
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ERC20PercentageTest> {
    return super.deploy(overrides || {}) as Promise<ERC20PercentageTest>
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {})
  }
  attach(address: string): ERC20PercentageTest {
    return super.attach(address) as ERC20PercentageTest
  }
  connect(signer: Signer): ERC20PercentageTest__factory {
    return super.connect(signer) as ERC20PercentageTest__factory
  }
  static readonly bytecode = _bytecode
  static readonly abi = _abi
  static createInterface(): ERC20PercentageTestInterface {
    return new utils.Interface(_abi) as ERC20PercentageTestInterface
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC20PercentageTest {
    return new Contract(address, _abi, signerOrProvider) as ERC20PercentageTest
  }
}
