/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from 'ethers'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import { TypedEventFilter, TypedEvent, TypedListener } from './commons'

interface KycRegisterInterface extends ethers.utils.Interface {
  functions: {
    'changeAdmin(address)': FunctionFragment
    'currentAdmin()': FunctionFragment
    'getKycStatusInfo(address)': FunctionFragment
    'getOperatorStatusInfo(address)': FunctionFragment
    'kycStatus(address)': FunctionFragment
    'operatorAccess(address)': FunctionFragment
    'setKycStatus(address,bool)': FunctionFragment
    'setOperatorStatus(address,bool)': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'changeAdmin', values: [string]): string
  encodeFunctionData(
    functionFragment: 'currentAdmin',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'getKycStatusInfo',
    values: [string]
  ): string
  encodeFunctionData(
    functionFragment: 'getOperatorStatusInfo',
    values: [string]
  ): string
  encodeFunctionData(functionFragment: 'kycStatus', values: [string]): string
  encodeFunctionData(
    functionFragment: 'operatorAccess',
    values: [string]
  ): string
  encodeFunctionData(
    functionFragment: 'setKycStatus',
    values: [string, boolean]
  ): string
  encodeFunctionData(
    functionFragment: 'setOperatorStatus',
    values: [string, boolean]
  ): string

  decodeFunctionResult(functionFragment: 'changeAdmin', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'currentAdmin',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getKycStatusInfo',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getOperatorStatusInfo',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'kycStatus', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'operatorAccess',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setKycStatus',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setOperatorStatus',
    data: BytesLike
  ): Result

  events: {}
}

export class KycRegister extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this

  listeners(eventName?: string): Array<Listener>
  off(eventName: string, listener: Listener): this
  on(eventName: string, listener: Listener): this
  once(eventName: string, listener: Listener): this
  removeListener(eventName: string, listener: Listener): this
  removeAllListeners(eventName?: string): this

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

  interface: KycRegisterInterface

  functions: {
    changeAdmin(
      newAdminAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    currentAdmin(overrides?: CallOverrides): Promise<[string]>

    getKycStatusInfo(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    getOperatorStatusInfo(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    kycStatus(arg0: string, overrides?: CallOverrides): Promise<[boolean]>

    operatorAccess(arg0: string, overrides?: CallOverrides): Promise<[boolean]>

    setKycStatus(
      userAddress: string,
      kycValue: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    setOperatorStatus(
      newOperatorAddress: string,
      isOperator: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>
  }

  changeAdmin(
    newAdminAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  currentAdmin(overrides?: CallOverrides): Promise<string>

  getKycStatusInfo(
    userAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>

  getOperatorStatusInfo(
    userAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>

  kycStatus(arg0: string, overrides?: CallOverrides): Promise<boolean>

  operatorAccess(arg0: string, overrides?: CallOverrides): Promise<boolean>

  setKycStatus(
    userAddress: string,
    kycValue: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  setOperatorStatus(
    newOperatorAddress: string,
    isOperator: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  callStatic: {
    changeAdmin(
      newAdminAddress: string,
      overrides?: CallOverrides
    ): Promise<void>

    currentAdmin(overrides?: CallOverrides): Promise<string>

    getKycStatusInfo(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>

    getOperatorStatusInfo(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>

    kycStatus(arg0: string, overrides?: CallOverrides): Promise<boolean>

    operatorAccess(arg0: string, overrides?: CallOverrides): Promise<boolean>

    setKycStatus(
      userAddress: string,
      kycValue: boolean,
      overrides?: CallOverrides
    ): Promise<void>

    setOperatorStatus(
      newOperatorAddress: string,
      isOperator: boolean,
      overrides?: CallOverrides
    ): Promise<void>
  }

  filters: {}

  estimateGas: {
    changeAdmin(
      newAdminAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    currentAdmin(overrides?: CallOverrides): Promise<BigNumber>

    getKycStatusInfo(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getOperatorStatusInfo(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    kycStatus(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

    operatorAccess(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

    setKycStatus(
      userAddress: string,
      kycValue: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    setOperatorStatus(
      newOperatorAddress: string,
      isOperator: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>
  }

  populateTransaction: {
    changeAdmin(
      newAdminAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    currentAdmin(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getKycStatusInfo(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getOperatorStatusInfo(
      userAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    kycStatus(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    operatorAccess(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    setKycStatus(
      userAddress: string,
      kycValue: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    setOperatorStatus(
      newOperatorAddress: string,
      isOperator: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>
  }
}
