/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides
} from 'ethers'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import { TypedEventFilter, TypedEvent, TypedListener } from './commons'

interface LicencableInterface extends ethers.utils.Interface {
  functions: {
    'createLicence(uint256,address,uint256)': FunctionFragment
    'getExpiration(uint256)': FunctionFragment
    'isLicence(uint256)': FunctionFragment
    'licenceOf(uint256)': FunctionFragment
  }

  encodeFunctionData(
    functionFragment: 'createLicence',
    values: [BigNumberish, string, BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'getExpiration',
    values: [BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'isLicence',
    values: [BigNumberish]
  ): string
  encodeFunctionData(
    functionFragment: 'licenceOf',
    values: [BigNumberish]
  ): string

  decodeFunctionResult(
    functionFragment: 'createLicence',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getExpiration',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'isLicence', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'licenceOf', data: BytesLike): Result

  events: {}
}

export class Licencable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this

  listeners(eventName?: string): Array<Listener>
  off(eventName: string, listener: Listener): this
  on(eventName: string, listener: Listener): this
  once(eventName: string, listener: Listener): this
  removeListener(eventName: string, listener: Listener): this
  removeAllListeners(eventName?: string): this

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

  interface: LicencableInterface

  functions: {
    createLicence(
      pid: BigNumberish,
      to: string,
      expirationDate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>

    getExpiration(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    isLicence(_id: BigNumberish, overrides?: CallOverrides): Promise<[boolean]>

    licenceOf(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>
  }

  createLicence(
    pid: BigNumberish,
    to: string,
    expirationDate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>

  getExpiration(
    _id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  isLicence(_id: BigNumberish, overrides?: CallOverrides): Promise<boolean>

  licenceOf(_id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

  callStatic: {
    createLicence(
      pid: BigNumberish,
      to: string,
      expirationDate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getExpiration(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    isLicence(_id: BigNumberish, overrides?: CallOverrides): Promise<boolean>

    licenceOf(_id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>
  }

  filters: {}

  estimateGas: {
    createLicence(
      pid: BigNumberish,
      to: string,
      expirationDate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>

    getExpiration(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    isLicence(_id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    licenceOf(_id: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>
  }

  populateTransaction: {
    createLicence(
      pid: BigNumberish,
      to: string,
      expirationDate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>

    getExpiration(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    isLicence(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    licenceOf(
      _id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>
  }
}
